#!/bin/sh

grep "|8080|iperfspeed" /etc/config.mesh/_setup.services.dmz &> /dev/null
DMZPRESENT=$?
grep "|8080|iperfspeed" /etc/config.mesh/_setup.services.nat &> /dev/null
NATPRESENT=$?
NODEMODE=$(uci -q -c /etc/local/uci/ get hsmmmesh.settings.config)

if [ "$DMZPRESENT" != 0 ]; then
  echo "IperfSpeed|1|http|$(uname -n)|8080|iperfspeed" >> /etc/config.mesh/_setup.services.dmz
fi

if [ "$NATPRESENT" != 0 ]; then
  echo "IperfSpeed|1|http|$(uname -n)|8080|iperfspeed" >> /etc/config.mesh/_setup.services.nat
fi

if [ "$NODEMODE" = "mesh" ]; then
  echo "Applying service announcement"
  /usr/local/bin/node-setup -a -p mesh &> /dev/null
  /etc/init.d/olsrd restart &> /dev/null
  echo "<br>"
fi

echo "Iperf Speed has been setup at http://$(uname -n):8080/iperfspeed"
echo "<br>"
echo "An advertised service has been added for Iperf Speed on the Services configuration page"

exit 0